---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: grafana
    group: grafana
  name: grafana
  namespace: logs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - env:
        - name: GF_EXPLORE_ENABLED
          value: "true"
        image: grafana/grafana:master
        name: grafana
        ports:
        - containerPort: 3000
      restartPolicy: Always
