---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
    group: grafana
  name: grafana
  namespace: logs
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    name: grafana
status:
  loadBalancer: {}
