apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: loki
    group: grafana
  name: loki
  namespace: logs
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: loki
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/local-config.yaml
        image: grafana/loki:master
        name: loki
        ports:
        - containerPort: 3100
      restartPolicy: Always
status: {}
