apiVersion: v1
kind: Service
metadata:
  labels:
    name: loki
    group: grafana
  name: loki
  namespace: logs
spec:
  ports:
  - name: "3100"
    port: 3100
    targetPort: 3100
  selector:
    name: loki
status:
  loadBalancer: {}
