---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

commonLabels:
  app: prometheus
resources:
  - account.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
configMapGenerator:
  - name: prometheus
    files:
      - prometheus.yml
images:
  - name: prom/prometheus
    newTag: v2.15.2