---
apiVersion: v1
kind: Namespace
metadata:
  name: logs
  labels:
    name: loki
    group: grafana
---
apiVersion: v1
kind: LimitRange
metadata:
  name: loki-range-limit
  namespace: logs
  labels:
    name: loki
    group: grafana
spec:
  limits:
  - default:
      cpu: "0.2"
      memory: "512Mi"
    defaultRequest:
      cpu: "0.1"
      memory: "256Mi"
    type: Container
