---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: loki

resources:
  - account.yml
  - daemonset.yml
  - promtail-cm.yml
  - psp.yml
  - role.yml
  - rolebinding.yml
  - secret.yml
  - service.yml
  - statefulset.yml

# secretGenerator:
#   - name: loki
#     files:
#       - secret.yml