---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: promtail
    group: grafana
  name: promtail
  namespace: logs
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/docker-config.yaml
        image: grafana/promtail:master
        name: promtail
        volumeMounts:
        - mountPath: /var/log
          name: var-logs
        - mountPath: /var/lib/docker/containers
          name: docker-logs
      restartPolicy: Always
      volumes:
      - name: var-logs
        hostPath:
          path: /var/log
          type: Directory
      - name: docker-logs
        hostPath:
          path: /var/lib/docker/containers
